---
development:
  cloud_name: dxiequkyq
  api_key: '538753987579689'
  api_secret: CwuZ0w041dTsgDL1hqht0svrRdw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dxiequkyq
  api_key: '538753987579689'
  api_secret: CwuZ0w041dTsgDL1hqht0svrRdw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dxiequkyq
  api_key: '538753987579689'
  api_secret: CwuZ0w041dTsgDL1hqht0svrRdw
  enhance_image_tag: true
  static_file_support: false
